version: '3.9'
services:
  coralogix-otel-exporter:
    platform: linux/amd64
    environment:
      - VERSION=$VERSION
    build:
      context: ./
    image: ghcr.io/coralogix/OTLP-GitHubAction-Exporter:$VERSION
